[LOCAL]
enable.hive = false
hive.database = null
kafka.topic = sdl_kafka_cloud
[QA]
enable.hive = true
hive.database = sdl_db_qa
kafka.topic = sdl_kafka_qa
[PROD]
enable.hive = true
hive.database = sdl_db
kafka.topic = sdl_kafka_kafka